<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link type='text/css' rel='stylesheet' href='css/style.css' />
        <script src="js/jquery-3.2.1.js"></script>
        <script src="js/main.js"></script>
    </head>
    <body>
        <div id="divmain">    
            <form action="listado" method="post" id="frmsearch">
                <fieldset>
                    <legend>Busqueda por Email</legend>
                    <input type="text" maxlength="50" id="email" name="email"/>
                    <input type="submit" value="Buscar" id="btnbuscar" name="btnbuscar" />
                </fieldset>
            </form>
            <div id="divresult">

            </div>
            <div id="divdetail">

            </div>
            
        </div>


    </body>
</html>
